title:            PAN
url:              http://ethansure.me    
permalink:        pretty
pygments:         true
markdown:         rdiscount
rdiscount:
  extensions:     [smart]
google_analytics: UA-45163660-1
paginate: 5
links: 
  - name:         关于
    url:          /about
  - name:         一悟
  	url:          /one