title:            PAN
description:      
url:              #ethansure.me
signoff:          # Your name.
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:             
  - name:         Tags
    url:          /tags.html
  - name:         About
    url:          /about

    external:     true
  - name:         Email
    url:          mailto:ethan.jianxu@gmail.com
    external:     true
  - name:         GitHub
    url:          http://github.com/ethanpan
    external:     true
pygments:         true
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]